/* When adding a topic card, also append a logbook entry in the same commit. */
(function (g) {
  g.LLB = g.LLB || {};
  /* Newest first. paper: K-1001…K-1005 or "site". topicId must match a real card id (empty for site-only). */
  g.LLB.logbook = [
    { date: "2026-09-21", type: "added", paper: "K-1001", topicId: "j-kelsen-pure", title: "Kelsen — Pure Theory: hierarchy, Grundnorm, dry bones", note: "Dedicated high-yield unpack so the Analytical parent stays a school survey. Purity, ought-science, Stufenbau pyramid, Grundnorm as presupposition, validity vs efficacy, sanction as directed coercive ought, State as legal order, 26 Jan 1950 reconstruction, dry-bones critiques, Austin/Salmond/Allen/Kelsen/Hart cast table. Full worked 20/10/4-markers from CCS public themes (≈2018–2024)." },
    { date: "2026-09-21", type: "added", paper: "K-1001", topicId: "j-indian-parallels", title: "Indian legal thought ↔ Western schools (side-by-side)", note: "Analogy, not identity. Dharma/śruti as moral-legal checksum (not Kelsen’s Grundnorm); Manu/smṛti; Kauṭilya’s four legs; daṇḍa vs mātsyanyāya; Rāma-rājya as cultural-constitutional memory. Hard hygiene: Veda ≠ Grundnorm; gold sentence is a critique of positivist dryness. Worked 10- and 20-markers plus the trap ‘Can Vedas be treated as Grundnorm?’" },
    { date: "2026-09-21", type: "updated", paper: "K-1001", topicId: "j-analytical", title: "Analytical School — Austin, Kelsen, H.L.A. Hart", note: "Kelsen kernel only; full Pure Theory 20-marker moved to j-kelsen-pure. Deep-links to Austin, Kelsen, Hart, AKH, and Indian parallels." },
    { date: "2026-09-21", type: "updated", paper: "site", topicId: "", title: "Book-bypass: worked answers + Jurisprudence one-home", note: "Cards now carry full hall-tempo model answers (not ‘pick an example’ prompts). Jurisprudence ch.1 split: intro = nature/utility; evolution rail = Rail|Matrix changelog; Sec A drill = unique shorts + pointers. Thinkers have one doctrine home; drills deepen one angle. Template worked answers also on Constitution nature, Torts intro, Crimes CH/murder, Contract English vs Indian consideration. Follow-up wave: fill remaining Const/Torts/Crimes/Contract against last-5-year CCS themes." },
    { date: "2026-09-21", type: "updated", paper: "K-1001", topicId: "j-pound-interests", title: "Pound’s classification of interests (and jural postulates)", note: "Replaced the ‘pick one Indian conflict’ homework prompt with three full model answers: Oleum gas / Vellore (environment vs industry), Indra Sawhney (reservation vs open competition), and a critique 10-marker (who weighs; friction is political)." },
    { date: "2026-09-21", type: "updated", paper: "K-1001", topicId: "j-intro", title: "Introduction — definition, nature, scope, importance", note: "No longer mounts the definition rail (that lives only on the evolution card). Sidebar subtitle is nature/scope/utility, not a third ‘Paranjape ch. 1’. Working defs only; full 2024 definition 20-marker written out." },
    { date: "2026-09-21", type: "updated", paper: "K-1001", topicId: "j-def-evolution", title: "Definitions — evolution of jurisprudence", note: "Still the only full Sem-1 Rail | Matrix. Explainer no longer re-walks school doctrine; Said/Challenged stay crisp. Worked 20-marker for ‘trace the evolution’." },
    { date: "2026-09-21", type: "updated", paper: "K-1001", topicId: "j-shorts", title: "Sec A drill — Manu, Stone, ‘eye of law’ (pointers for Bentham/Salmond)", note: "Not a third ch.1 essay. Unique homes: Manu, Stone, Holland’s eye of law. Bentham/Salmond/Austin are recitation + pointer. Full 4-marker model answers." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-def-evolution", title: "Definitions — evolution of jurisprudence", note: "Matrix study-sheet added as a second layout (Rail | Matrix toggle). Same Sem-1 beats: Era, Name, Where, school chip, Landmark, Said, Challenged. Footer mnemonics A→K→H, I→D→P, B-A-H-G-S-P. Left-rail unchanged." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-def-evolution", title: "Definitions — evolution of jurisprudence", note: "Where field on every Sem-1 thinker (Greece, Roman Empire, Italy, England, Germany, France, Austria, New Zealand, Australia/England, United States) so the map sits next to the doctrine." },
    { date: "2026-09-17", type: "updated", paper: "site", topicId: "", title: "Evolution timelines UI — left-rail diagram", note: "Every timeline is a vertical rail on the left with dots on the line; each node is an inline card (Era/Year, Who, Landmark, What they said, What they pushed back against). No disconnected table under the rail. Mobile: cards stay to the right of the rail." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-def-evolution", title: "Definitions — evolution of jurisprudence", note: "Holistic Sem-1 rail (20 named beats: Ulpian, Aquinas, Bentham, Austin, Savigny, Maine, Marx, Ihering, Holland, Salmond, Stammler, Gray, Kohler, Duguit, Pound, C.K. Allen, Realists, Kelsen Grundnorm, Hart). ABAH-GSP kept as gold inset; A→K→H and I→D→P mnemonic chips." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-intro", title: "Introduction — definition, nature, scope, importance", note: "Same left-rail diagram as the dedicated definitions card (full Sem-1 cast, inline cards, no leftover table)." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-def-evolution", title: "Definitions — evolution of jurisprudence", note: "Dedicated card: vertical timeline, gold spine (ought → command → form → courts → first principles → social ends), ABAH-GSP mnemonic, thinker table, PYQ outline." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-intro", title: "Introduction — definition, nature, scope, importance", note: "Compact definitions-evolution timeline on the intro card; pointer to the dedicated teaching spine." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-natural", title: "Natural Law — classical and revival (Stammler, Kohler)", note: "Timeline: classical NL → early-modern rights → Austin eclipse → Stammler/Kohler revival." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-analytical", title: "Analytical School — Austin, Kelsen, H.L.A. Hart", note: "Timeline: command (1832) → pure pyramid (1934) → primary/secondary rules (1961)." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-historical", title: "Historical School — Savigny and Sir Henry Maine", note: "Timeline: Savigny 1814 Volksgeist → Maine 1861 status-to-contract." },
    { date: "2026-09-17", type: "updated", paper: "K-1001", topicId: "j-socio", title: "Sociological School — Pound and Duguit", note: "Timeline: Ihering purpose → Ehrlich living law → Duguit solidarity → Pound social engineering." },

    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-21", title: "Article 21 — life and personal liberty", note: "Timeline: Gopalan 1950 → Maneka 1978 → Puttaswamy 2017." },
    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-fr-dpsp-cases", title: "FR vs DPSP — Champakam, Golaknath, Kesavananda, Minerva Mills", note: "Timeline: Golaknath 1967 → Kesavananda 1973 → Minerva Mills 1980." },
    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-15-16-reservation", title: "Articles 15–16 — reservation, Indra Sawhney, EWS / Janhit", note: "Timeline: Indra Sawhney 1992 → Nagaraj/Jarnail promotions → 103rd EWS / Janhit 2022." },
    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-19a", title: "Freedom of speech and expression — Art. 19(1)(a)", note: "Timeline: Romesh Thappar 1950 → Sakal/Bennett Coleman → Shreya Singhal 2015." },

    { date: "2026-09-17", type: "updated", paper: "K-1003", topicId: "t-strict", title: "Strict liability and absolute liability", note: "Timeline: Rylands 1868 (strict, with excuses) → M.C. Mehta 1987 (absolute)." },
    { date: "2026-09-17", type: "updated", paper: "K-1003", topicId: "t-vicarious", title: "Vicarious liability, State / sovereign immunity, joint tortfeasors", note: "Timeline: P&O/Vidyawati → Kasturilal 1965 → Nilabati Behera / Nagendra Rao 1993–94." },
    { date: "2026-09-17", type: "updated", paper: "K-1003", topicId: "t-negligence", title: "Specific tort — Negligence", note: "Timeline: Donoghue 1932 neighbour principle → Indian reception (Subhagwanti / Jacob Mathew)." },

    { date: "2026-09-17", type: "updated", paper: "K-1004", topicId: "cr-general", title: "General principles — crime, elements, stages, strict & constructive liability, common intention & common object", note: "Timeline: IPC 1860 → sedition 124A/Kedarnath → Joseph Shine adultery death → BNS 2023 (152, organised crime, 497 omitted)." },
    { date: "2026-09-17", type: "updated", paper: "K-1004", topicId: "cr-homicide", title: "Offences against the human body — culpable homicide, murder, rash/negligent death", note: "Timeline: common-law malice → IPC 299/300 → BNS 100/101 numbering map (code evolution, not a new philosophy)." },

    { date: "2026-09-17", type: "updated", paper: "K-1005", topicId: "k-eng-vs-indian", title: "English vs Indian law of consideration", note: "Timeline: Eastwood/Tweddle locks → s.2(d) 1872 + Chinnaya 1882 fork." },
    { date: "2026-09-17", type: "updated", paper: "K-1005", topicId: "k-discharge", title: "Discharge of contracts, with special reference to frustration", note: "Timeline: Taylor 1863 / Krell 1903 → Satyabrata 1954 (hardship ≠ frustration)." },
    { date: "2026-09-17", type: "updated", paper: "K-1005", topicId: "k-standard", title: "Standard form contracts", note: "Timeline: Olley/Thornton notice ladder → CPA 2019 unfair-contract overlay." },

    { date: "2026-09-17", type: "added", paper: "site", topicId: "", title: "Evolution timelines UI", note: "Reusable vertical timeline (year badge → name → doctrine → what it replaced). Data in js/content/timelines.js." },
    { date: "2026-09-17", type: "added", paper: "site", topicId: "", title: "Logbook tab introduced", note: "What’s-new list with filters; titles jump to the live topic card." },

    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-akh", title: "Drill — Austin vs Kelsen vs Hart", note: "Standalone comparison table for the distinguish 10-marker." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-shorts", title: "Sec A shorts — Bentham, Manu, Salmond, Stone, ‘eye of law’", note: "Annual 4-markers lifted out of the intro essay." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-hist-vs-legalhist", title: "Distinction — Historical Jurisprudence vs Legal History", note: "Dedicated 10-mark card: logbook vs hypothesis." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-law-morals", title: "Law and morals", note: "Dec 2023 Sec B spine, split from j-intro." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-austin-cmd", title: "Austin — command, sovereign, sanction", note: "Unpacked command theory for the 20-marker." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-hart-rules", title: "Hart — primary and secondary rules", note: "Recognition, change, adjudication drill." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-analytical-vs-natural", title: "Analytical vs Natural school", note: "Stock distinguish table." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-socio-vs-hist", title: "Sociological vs Historical school", note: "Pound/Duguit vs Savigny/Maine." },
    { date: "2026-09-17", type: "added", paper: "K-1001", topicId: "j-pound-interests", title: "Pound’s classification of interests (and jural postulates)", note: "IPS inventory + postulates short." },

    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-21a", title: "Article 21A — Right to Education", note: "86th timeline, RTE 2009, Unni Krishnan → Pramati." },
    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-23-24", title: "Right against exploitation — Articles 23–24", note: "Begar, PUDR, Bandhua, Mehta child labour." },
    { date: "2026-09-17", type: "updated", paper: "K-1002", topicId: "c-duties", title: "Fundamental Duties — Article 51A", note: "Full (a)–(k) list for Dec 2024 ‘any four’." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-emergency-fr", title: "Emergency suspension of Fundamental Rights", note: "358 vs 359; 44th lock on 20/21." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-art13-doctrines", title: "Article 13 — eclipse, severability, waiver", note: "2022-style doctrines pack." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-32-writs", title: "Writs under Article 32 — HMPCQ", note: "Five writs drill under the PIL essay." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-art12-state", title: "State under Article 12", note: "Ajay Hasia / Biswas instrumentality tests." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-14-classification", title: "Article 14 — reasonable classification", note: "Intelligible differentia + rational nexus." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-15-16-reservation", title: "Reservation under Articles 15–16", note: "Indra Sawhney → EWS spine." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-19-suite", title: "Article 19 suite — traps beyond 19(1)(a)", note: "Exam-trap sheet; CCS lists only speech." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-21-privacy", title: "Article 21 — privacy, dignity, livelihood", note: "Puttaswamy line unpacked." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-fr-dpsp-cases", title: "FR ↔ DPSP case ladder", note: "Champakam–Golaknath–Kesavananda–Minerva." },
    { date: "2026-09-17", type: "added", paper: "K-1002", topicId: "c-300a", title: "Article 300A — right to property (bridge card)", note: "44th demotion; 2022 shorts insurance." },

    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-nervous-shock", title: "Nervous shock (psychiatric injury)", note: "Dec 2024 Sec B under negligence." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-res-ipsa", title: "Res ipsa loquitur", note: "Dec 2024 Sec A; three conditions; evidence not a tort." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-medical-neg", title: "Medical and professional negligence", note: "Bolam / Jacob Mathew / Shantha overlay." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-contributory", title: "Contributory vs composite negligence", note: "Apportionment vs joint-and-several." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-service-vs-for", title: "Contract of service vs contract for service", note: "Elevated CPA syllabus bullet." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-who-may-sue", title: "Who may sue and who may be sued in tort", note: "Bangia capacity chapter as its own card." },
    { date: "2026-09-17", type: "updated", paper: "K-1003", topicId: "t-nuisance", title: "Specific tort — Nuisance", note: "Public/private, defences, particular damage." },
    { date: "2026-09-17", type: "updated", paper: "K-1003", topicId: "t-trespass", title: "Specific tort — Trespass", note: "Person, land, and goods deepened." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-pigeonhole", title: "Pigeon-hole theory (Salmond)", note: "Dec 2024 Sec A short." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-remoteness", title: "Remoteness of damage — Wagon Mound", note: "Kind vs directness." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-rylands-elements", title: "Rylands v Fletcher — elements and exceptions", note: "Strict-liability kit." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-mehta-absolute", title: "Absolute liability — M.C. Mehta", note: "Oleum gas; no Rylands exceptions." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-kasturilal", title: "State liability — Kasturilal to Nagendra Rao", note: "Sovereign/non-sovereign death." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-defamation-defences", title: "Defamation — defences in full", note: "Truth, fair comment, privilege." },
    { date: "2026-09-17", type: "added", paper: "K-1003", topicId: "t-cpa-hierarchy", title: "CPA 2019 — commission hierarchy, unfair trade, product liability", note: "2021 pecuniary bands; Forums are dead." },

    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-dowry-death", title: "Dowry death — BNS vs IPC (Dec 2024 20-marker)", note: "BNS 80 carries 304B’s four limbs + presumption." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-stalking", title: "Stalking (BNS 78)", note: "Dec 2024 Sec A; 354D ancestor." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-insanity", title: "Legal insanity vs medical insanity", note: "s.22 cognitive test vs diagnosis." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-wr-riot", title: "Distinguish — wrongful restraint vs confinement; rioting vs affray", note: "2023 Sec C double distinguish." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-stages", title: "Stages of crime — intention, preparation, attempt, commission", note: "Full I-P-A-C essay spine (Dec 2024 Sec C)." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-defs-shorts", title: "Definition shorts — dishonestly, injury, wrongful loss, good faith, movable property", note: "Dec 2023 Sec A pack." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-child", title: "Offences against child under BNS", note: "Dec 2024 optional; POCSO sits beside." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-snatching", title: "Snatching (BNS 304)", note: "BNS novelty between theft and robbery." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-bns152", title: "Sedition → BNS 152 (do not paste a 124A essay)", note: "Rewrite drill vs old sedition." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-hurt-gh", title: "Hurt vs grievous hurt (the eight-clause list)", note: "Recite BNS 116 / IPC 320." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-attempt-prep", title: "Attempt vs preparation (and when the line is crossed)", note: "Proximity tests; BNS 62 residual." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-mens-rea", title: "Mens rea and strict / statutory offences", note: "Guilty mind unpacked." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-mistake", title: "Mistake of fact vs mistake of law", note: "ss.14/17 cluster." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-intoxication", title: "Intoxication — involuntary vs voluntary", note: "ss.23–24." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-pd-limits", title: "Private defence — when it extends to death", note: "s.38 / s.41 lists." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-murder-exceptions", title: "Murder exceptions (the five)", note: "Grave and sudden, excess PD, etc." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-theft-ladder", title: "Theft vs extortion vs robbery vs dacoity (the ladder)", note: "303–310 climb." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-cheating", title: "Cheating — essentials (BNS 318)", note: "Intention at inception." },
    { date: "2026-09-17", type: "added", paper: "K-1004", topicId: "cr-unlawful-assembly", title: "Unlawful assembly — essentials and common object", note: "189/190 vs 3(5)." },

    { date: "2026-09-17", type: "updated", paper: "K-1005", topicId: "k-contingent", title: "Contingent contracts (Ss. 31–36)", note: "ss.32–36 enforcement tree." },
    { date: "2026-09-17", type: "updated", paper: "K-1005", topicId: "k-standard", title: "Standard form contracts", note: "Notice ladder + CPA 2019 unfair contract." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-novation", title: "Novation, rescission, alteration (S. 62)", note: "Dec 2024 Sec A novation." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-wager-contingent", title: "Wager vs contingent contract", note: "Insurance / lottery / crossword / speculative checklist." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-eng-vs-indian", title: "English vs Indian law of consideration", note: "Dec 2024 20-marker table; 2(d) vs privity trap." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-discharge-checklist", title: "Modes of discharge — printable checklist", note: "P-A-I-B-L for Dec 2024 Sec C." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-quantum-meruit", title: "Quantum meruit", note: "As much as earned; s.65/s.70 neighbourhood." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-offer-vs-itt", title: "Proposal vs invitation to treat", note: "Shop displays, tenders, auctions." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-comm-revocation", title: "Communication and revocation (Ss. 4–6)", note: "Postal rule vs instantaneous." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-past-consideration", title: "Past consideration, executory consideration, and s.25", note: "Three tenses + three s.25 doors." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-privity-exceptions", title: "Privity of contract — Indian exceptions", note: "Trust, family, acknowledgement, land, statute." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-minor-restitution", title: "Minor’s agreement — consequences and restitution", note: "Mohori Bibee; s.68." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-consent-matrix", title: "Coercion vs undue influence vs fraud vs misrepresentation", note: "CUFM matrix; silence ≠ fraud." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-restraints", title: "Agreements in restraint of marriage, trade, and legal proceedings", note: "ss.26–28." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-frustration-limits", title: "Frustration — limits (what s.56 will not kill)", note: "Hardship ≠ frustration." },
    { date: "2026-09-17", type: "added", paper: "K-1005", topicId: "k-hadley", title: "Remoteness of damage — Hadley and s.73", note: "Two limbs; mitigation." }
  ];
})(window);
