/* Full hall-tempo model answers. Original teaching prose from public CCS themes,
   syllabus, and landmark holdings. Not Unique/Nitin, not textbook paste. */
(function (g) {
  g.LLB = g.LLB || {};

  function A(year, section, marks, title, paras) {
    return {
      year: year,
      section: section,
      marks: marks,
      title: title,
      answer: paras.map(function (p) { return "<p>" + p + "</p>"; }).join("")
    };
  }

  g.LLB.workedAnswers = {
    "j-pound-interests": [
      A("Dec 2024 & 2023", "C", "20", "Social engineering — environment vs industry (Oleum gas / Vellore as the engineering act)", [
        "Roscoe Pound described law as social engineering: a process of satisfying the maximum of wants with the minimum of friction and waste. The metaphor is empty unless the engineer can name the claims that collide. Pound inventories three families. <strong>Individual interests</strong> cover personality (body, honour, privacy), domestic relations, and substance (property, succession, contract, employment). <strong>Public interests</strong> are those of the State as a juristic person — efficient administration, territorial integrity, the fiscus. <strong>Social interests</strong> include general security, security of social institutions, general morals, conservation of social resources, general progress, and the social interest in individual life — the claim to a human existence, the bridge to Article 21. Behind the inventory sit <strong>jural postulates</strong>: background assumptions a civilisation treats as reasonable — that others will not commit intentional aggression; that they will control things they have created or discovered; that they will keep bargains; that they will act with due care; that they will control dangerous things they maintain. Postulates change. That is how Pound stays historicist without becoming Savigny.",
        "The Indian collision is not a blank to fill in later. In <em>M.C. Mehta v Union of India</em> (Oleum Gas Leak, 1986–87) oleum escaped from Shriram’s Delhi plant. The <em>individual interest in substance</em> — an enterprise’s claim to run a chemical works, and workers’ claim to employment — collided with the <em>social interest in general security</em> and in <em>conservation of social resources</em> (the health of a dense city; air and water as shared resources) and with the <em>social interest in individual life</em> under Article 21. The Supreme Court did not treat this as Austin’s sovereign barking a command. It engineered a new liability rule: an enterprise engaged in hazardous or inherently dangerous activity is <strong>absolutely liable</strong> for the harm it causes; the excuses that travel with <em>Rylands v Fletcher</em> (act of God, plaintiff’s default, statutory authority, act of a stranger, consent) do not apply; the measure of compensation is correlated to the magnitude and capacity of the enterprise. That is Pound’s scheduler rewriting a jural postulate: people who maintain dangerous things must actually control them, and the cost of failure is not dumped on neighbours.",
        "<em>Vellore Citizens’ Welfare Forum v Union of India</em> (1996) then named the tools. Tanneries in Tamil Nadu had polluted the Palar. Individual substance and economic progress collided again with conservation and health. The Court read the <strong>precautionary principle</strong> and the <strong>polluter-pays principle</strong> into Indian environmental law as part of the law of the land, tying them to Articles 21, 47, 48A and 51A(g). Precaution is engineering under uncertainty: where there is a risk of serious and irreversible harm, want of full scientific certainty is not a licence to keep emitting. Polluter pays allocates the cost of friction to the process that created it. Environment (Protection) Act 1986 and the later National Green Tribunal statute are the legislative side of the same engineering act.",
        "Close: a 20-marker on social engineering that never names two colliding interests and a court or statute as the scheduler has only recited a slogan. Oleum gas and Vellore are the Indian sentences. The limit on the metaphor — who weighs, and whether “friction” is a political word — is the next answer on this card."
      ]),
      A("theme 2020–25", "C", "20", "Social engineering — reservation vs open competition (Indra Sawhney as the engineering act)", [
        "Start again from the inventory, because CCS will fail a Pound essay that never classifies. Individual interests include the claim to a career on open competition — personality (dignity of equal treatment) and substance (livelihood, office). Social interests include the security of political and social institutions and the social interest in individual life for groups historically locked out of public employment and education. Public interest, in a thinner sense, is the State’s claim to an efficient administration. Reservation is the scheduler’s attempt to satisfy more of those claims with less long-run waste, not a midnight Austinian bark.",
        "The engineering act is Articles 15(4) and 16(4), read with the case ladder. <em>State of Madras v Champakam Dorairajan</em> (1951) treated communal quotas as a breach of equality; the First Amendment inserted 15(4) so the scheduler could keep working. <em>Indra Sawhney v Union of India</em> (1992) is the full retune: 16(4) is a facet of equality, not its enemy; backwardness plus inadequate representation; a general ceiling of fifty per cent; creamy-layer exclusion for Other Backward Classes; no reservation in promotions as the original holding (later legislative and judicial history on SC/ST promotions is a Consti drill, not this paragraph). The Court is weighing individual open-competition against the social interest in a representative public service. <em>Janhit Abhiyan</em> (2022) on the 103rd Amendment (EWS) is a later retune of the same machine: another classified claim, another fight about whose friction counts.",
        "A labour-and-contract cousin, if the question stretches: Maine’s status-to-contract high-water is the Contract Act’s freedom of agreement. Factories, industrial-disputes, minimum-wages and bonded-labour statutes (<em>Bandhua Mukti Morcha</em> is the Article 21 landing) re-introduce status as protective classification. Pound would call that engineering. Maine would call it a return to status. Write the collision; do not write a labour-code digest.",
        "Close: reservation is Pound in constitutional clothes. Name IPS, name 15(4)/16(4), name Indra Sawhney, then spend one paragraph on the critique (next answer) — who sits at the console, and whether fifty per cent is science or politics."
      ]),
      A("theme", "B", "10", "Critique of social engineering — who weighs, and why “friction” is political", [
        "Pound’s picture is powerful for an Indian paper because courts and legislatures actually do schedule overlapping claims. The critique must still be written in full, not hinted as “mention critiques.” First: <strong>who weighs?</strong> In Oleum gas, Vellore, Indra Sawhney and Minerva Mills it is often unelected judges, or a Parliament that does not publish an IPS spreadsheet. The engineering metaphor hides a political choice about whose want counts. Second: <strong>measuring friction and waste is not a thermometer reading.</strong> American progressive-era confidence assumed experts could balance; a caste society and a federal bargaining table do not yield a single “minimum waste” number. Third: <strong>American bias</strong> — Pound wrote for a common-law industrial democracy. Transplanting his QoS classes onto Directive Principles and PIL does useful work, but it is still a transplant. Fourth: the <strong>Marxist reply</strong> — claimants do not arrive equal; the plant’s owners and the slum-dwellers are not two processes on a fair scheduler; law can be superstructure that stabilises a mode of production. Fifth: a <strong>Savigny reply</strong> — rules that ignore how a people actually live will be paper law (Ehrlich’s living law is the sociological cousin of that warning).",
        "Indian landing: Article 21 environmental expansion and reservation ceilings are both engineering acts that remain contested. The honest close is not “Pound is wrong.” It is: Pound names the job (maximise satisfied claims, minimise friction); he does not give a value-free scales. A first-class 10-marker states the five critiques, lands one Indian example, and still keeps Pound as the best vocabulary CCS has for why Mehta and Indra Sawhney are the same kind of legal act."
      ])
    ],

    "j-intro": [
      A("Dec 2024", "C", "20", "How would you define Jurisprudence? Which definition is most appropriate?", [
        "Jurisprudence is not the municipal law of India, England, or Rome. It is the systematic study of the concept of law — what counts as law, how it binds, where it comes from, and how it relates to the State, morals, and society. If the answer is “it is Indian law,” the writer has confused jurisprudence with a code. If the answer is “philosophy with no courtroom use,” the writer has abandoned the marks for utility.",
        "Named definitions, each with one limit. Austin (1832): jurisprudence is the philosophy of positive law — law as it <em>is</em>, laid down by a political superior. Limit: custom, constitutions that bind the legislature, and international law fall out of “law properly so called.” Holland (1880): the formal science of positive law — the form of right, duty, and person, not the contents of the BNS. Limit: form can look empty of justice and of social facts. Salmond (1902): the science of the first principles of the civil law. Limit: courtroom-facing, still thin on sociology. Gray (1909): law is what courts do; jurisprudence states the rules they apply. Limit: legislation and custom wait for a bench. Pound (c. 1922): law as social engineering, reconciling overlapping claims with minimum friction. Limit: who weighs the interests?",
        "The most appropriate definition for an Indian courtroom paper is a hybrid: Salmond’s first principles oriented to Pound’s social task. First principles keep the answer from dissolving into politics; social task keeps it from being Holland’s empty form. Bentham is the reform-engine cousin of Austin (utility; “nonsense upon stilts”); he is not a sixth beauty-contest quotation unless the question stretches to evolution — that changelog lives on the definition-evolution rail.",
        "Nature: the subject is abstract (concepts), comparative (command next to Volksgeist next to prediction-of-courts), and a meta-layer rather than a seventh code. Scope in CCS Sem-1 is school-heavy: Natural, Analytical, Historical, Sociological, Realist, Marxist. Utility: clarity of concepts; critique of legislation; professional self-consciousness (Stone’s lawyers’ extroversion). Indian landing: <em>Kesavananda Bharati</em> (1973) is legal theory leaking into doctrine — constituent power is not Austin’s legally unlimited sovereign. Close: define with names, pick Salmond-plus-Pound, then spend the last third on nature, scope and utility so the 2024 verb “which is most appropriate” is actually answered."
      ]),
      A("Dec 2024", "A", "4", "Is Jurisprudence the study of the law of one nation?", [
        "No. Jurisprudence is the science or philosophy of law as such — the form and theory of legal order — not the statute book of one State. Austin still studied as an English thinker in an Indian paper; Ulpian’s <em>jurisprudentia</em> is examinable in Meerut without making the candidate a Roman lawyer. Holland’s “formal science of positive law” is the shortest citation: we study the form of right and duty, not the contents of the BNS. One-line close: if it were the law of one nation, K-1001 would be a smaller Constitutional Law paper."
      ])
    ],

    "j-def-evolution": [
      A("theme 2018–25", "C", "20", "Trace the evolution of the definition of jurisprudence. Which definition is most appropriate?", [
        "The fail mode is five unnamed quotations. The pass mode is a dated chronological arc: each thinker inherits a problem with the word “jurisprudence” and ships a new job for it. Gold inset, definition jobs only: Bentham → Austin → Holland → Gray → Salmond → Pound — ought, command, form, courts, first principles, social ends (B-A-H-G-S-P). That inset is not the whole rail.",
        "Walk the rail in year order, two sentences a beat. Ulpian: <em>jurisprudentia</em> as the science of giving each their due — justice, not only the prince’s will. Aquinas: human law participates in eternal law; an unjust enactment is a corruption of law. Bentham (IPML 1789; <em>Anarchical Fallacies</em> c. 1791): utility is the test; natural-rights talk is “nonsense upon stilts”; codify and censor. Austin (1832): philosophy of positive law; command of a political superior. Savigny (1814) and Maine (1861) shift the job toward growth — Volksgeist; status to contract — even though they are not “definition” names in the gold six. Holland (1880): formal science. Salmond (1902, slightly before Gray): first principles of civil law. Gray (1909): courts. Stammler and Kohler revive a measured ought (variable content; culture). Duguit and Pound: solidarity and social ends. American Realists: law in action. Kelsen: Grundnorm pyramid. Hart (1961): primary and secondary rules. Marx (1859): superstructure. Date hygiene: Salmond predates Gray on the badge; Holmes 1897 seeds Realism earlier than the school’s slot after Pound.",
        "Most appropriate: Salmond plus Pound — first principles aimed at a social task — because an Indian 20-marker must still work in a courtroom that also runs Article 21 and labour statutes. Austin is too narrow for a limited Constitution; Holland is too empty; Gray waits for a bench; Bentham’s ought is a reform calculator, not a validity test. Close with one Indian landing for utility (<em>Kesavananda</em>) and a refusal to mash A→K→H or I→D→P into the definition parade: those are school kernels, not extra definition jobs."
      ]),
      A("stock distinguish", "B", "10", "Austin and Salmond on jurisprudence", [
        "Austin: jurisprudence is the philosophy of positive law. Law properly so called is the general command of a legally unlimited sovereign, habitually obeyed, backed by a sanction. International law and constitutional conventions are positive morality. The job of the word is to mark the <em>is</em> of a political superior’s order.",
        "Salmond: jurisprudence is the science of the first principles of the civil law — the body of principles the State recognises and applies in the administration of justice. The job of the word is courtroom grammar: right, duty, procedure, not a barking person.",
        "Indian landing: Austin struggles the moment Article 13 and basic structure legally limit the highest law-making body. Salmond still has something to say in that courtroom, which is why a hybrid close (Salmond’s first principles plus Pound’s social task) scores. Do not mash Holland into Austin: Holland is form, not a second sovereign."
      ])
    ],

    "j-shorts": [
      A("Dec 2024 / 2023", "A", "4", "Bentham’s contribution (do not restart Austin)", [
        "Jeremy Bentham is the utilitarian reformer of the analytical family. The test of law is the greatest happiness of the greatest number — a pain-and-pleasure calculus. He is expositor and censor: he describes law as command, and he asks what the statute book ought to become. Natural-rights talk is “nonsense upon stilts.” He wants codes, not a fog of common-law fictions. Indian landing: the very idea of a comprehensive penal code (IPC 1860, now BNS) is a Benthamite instinct. Contrast, then sit down: Austin is drier — philosophy of positive law <em>as it is</em>, sovereign plus sanction, less the reformer. Bentham supplies the reform engine; Austin supplies the command definition the 20-marker quotes. Do not write Kelsen."
      ]),
      A("Dec 2024", "A", "4", "Manu", [
        "Manu is the Indian opening Section A still loves. The <em>Manusmriti</em> is a Dharmaśāstra source: law mixed with dharma, a duty-order of a civilisation, the king as enforcer of an already-there dharma — not Austin’s legally illimitable political superior who <em>makes</em> law by barking. Validity is not only a command. Colonial codes later overwrote much of this as municipal law (IPC 1860, Contract Act 1872). That overwrite is the Historical-school critique of midnight legislation, not a caste pamphlet and not a modern Hindu-code essay. Close: Indian jurisprudence has a textual root older than Austin, and it is pre-analytical — duty before command."
      ]),
      A("Dec 2023 / 2024", "A", "4", "Julius Stone — “lawyers’ extroversion”", [
        "Stone: jurisprudence is lawyers’ extroversion — the lawyer looking <em>outward</em> from doctrine toward philosophy, sociology, economics, history. It is not introverted case-cramming. Utility landing: K-1001 exists so a statute can be criticised, not only recited. Contrast: Gray and Holmes still look inward to official behaviour (“law is what courts do”); Stone leaves the library. A Pound essay that never mentions overlapping claims, or an Austin essay that never mentions Article 13, has failed Stone’s test."
      ]),
      A("theme", "A", "4", "“Eye of law” / Holland", [
        "Holland’s jurisprudence is the formal science of positive law. The legal “eye” watches the form of jural relations — right, duty, person, ownership — not the contents of one code and not moral deserts. Limit in one sentence: Realists say an eye that never watches what courts actually do is blind; Pound says an eye that never watches social ends is idle. Do not mash Holland into Austin: form is not a barking sovereign."
      ])
    ],

    "j-natural": [
      A("theme 2018–25", "C", "20", "Classical Natural Law and its 20th-century revival, with Stammler and Kohler", [
        "Natural law is the claim that human law is answerable to reason, justice, or the moral architecture of human association — not only to a superior’s command. Classical strand: Aristotle’s natural versus conventional justice; Cicero’s true law as right reason in agreement with nature; Aquinas — <em>lex humana</em> participates in <em>lex aeterna</em> via natural law; an unjust law is a corruption of law (<em>lex injusta non est lex</em>, handled as a measure, not a riot permit). Grotius secularises the tradition (“even if God did not exist”); Locke ties it to rights the State does not create.",
        "Why it died in the nineteenth century: science-envy and sovereignty theory. If law is the sovereign’s command, “higher law” looks like smuggling morals into validity. Austin’s province is a demolition job on natural-law vagueness. Revival in the twentieth: world wars, genocidal “legal” systems, the sense that a purely formal validity test baptises atrocity. Radbruch’s formula — extreme injustice is not law — is the European political proof, even when CCS names Stammler and Kohler rather than Radbruch.",
        "Rudolf Stammler: “natural law with a variable content.” There is no eternal code of detailed rules; there is a method of just law — a community of free-willing persons whose legal form aims at harmony of purposes. The protocol is stable; the payload changes with society. Josef Kohler: neo-Hegelian cultural interpretation. Law is a product of civilisation’s cultural evolution; jural postulates of a civilisation grow as culture grows. Pair Kohler with Savigny: both historicise law, but Kohler is progressive/cultural rather than Volksgeist-romantic.",
        "Indian landing, without overclaim: Directive Principles, “justice — social, economic, political” in the Preamble, <em>Maneka Gandhi</em> (1978) reading “procedure established by law” as just, fair and reasonable, and <em>Kesavananda</em> basic structure as a higher-law analogue. The Constitution is not Aquinas. Indian public law never fully accepted “law is law because it is commanded.” Critiques: vagueness; whose reason?; judges as philosopher-kings; Stammler’s form can be empty; Kohler under-specifies institutions. Close: classical NL measures positive law; Stammler keeps the measure and historicises the content; Kohler historicises through culture; Indian public law uses both the pedigree of Article 13 and the morality of the Preamble."
      ]),
      A("theme", "B", "10", "“Natural law with a variable content” (Stammler)", [
        "Stammler’s slogan answers the oldest objection to natural law: if nature is eternal, how can property rules change? His reply is Kantian form plus historical payload. There is a method of just law — a community of free-willing persons, harmony of individual purposes — that stays stable as a protocol. The detailed rules (the payload) vary with social conditions. That is “natural law with a variable content.” Contrast Austin: validity is pedigree of command, not justness of form. Contrast Aquinas: Stammler does not need a theology of eternal law. Contrast Savigny: Stammler is not waiting for Volksgeist; he still has a just-law test. Indian echo: a Constitution that keeps equality as form while reservation and labour statutes change the payload is a Stammler sentence, not a proof that India “is” Stammler. Limit: the form can be empty if “harmony of purposes” never decides a hard case."
      ])
    ],

    "j-analytical": [
      A("Dec 2024", "C", "20", "Describe Hans Kelsen’s pure theory of law", [
        "Kelsen’s programme is purity: strip the science of law of sociology, psychology, and morals. Law is a system of norms, each authorised by a higher norm, terminating in a presupposed <strong>Grundnorm</strong> — “the historically first constitution ought to be obeyed” — which is not proved inside the system. A norm’s validity is membership in this chain, not its justice. Sanction is a directed coercive act stipulated by a norm, not Austin’s threatened “evil” attached to a person-sovereign. The State is the legal order personified; there is no dualism of a man standing behind the law.",
        "Indian illustration, written in full: 26 January 1950 can be taught as a Grundnorm shift from colonial legality to “the Constitution of India ought to be obeyed.” Delegated legislation and bye-laws then sit on lower rungs — valid if authorised, not because they are just. The basic-structure fight is a fight about whether even the highest amending norm is unconditioned. Kelsen would be uneasy with a judicial super-norm. That unease is the interesting sentence. Do not write “Grundnorm = Constitution” as an identity.",
        "Critiques: the Grundnorm is a fiction; purity is impossible (someone still chooses the base); revolutions are explained only by a new presupposition; the theory is empty of justice. Residual use: it kills the picture of law as a man’s bark, and it gives a vocabulary for validity chains (Article 13, subordinate legislation). Contrast in one paragraph: Austin’s determinate sovereign versus Kelsen’s impersonal pyramid; Hart’s practised rule of recognition versus Kelsen’s transcendental ought. Close: pure theory is a map of membership, not a sermon, and that is both its power and its limit."
      ]),
      A("Dec 2023", "C", "20", "“Jurisprudence is the philosophy of Positive Law” (Austin) — Discuss", [
        "The quotation is Austin’s province: jurisprudence studies positive law, law set by political superiors to inferiors, not divine law and not positive morality. Law properly so called is a general command of a sovereign — a determinate person or body, not in habit of obedience to a like superior, habitually obeyed by the bulk of an independent political society — backed by a sanction. International law, club rules, and (on his terms) much of constitutional convention become positive morality. Bentham is the cousin, not the twin: Bentham censors and wants codes on a utility calculus; Austin exposes what law is.",
        "Indian landing: Parliament looks Austinian until Article 13, judicial review, federal lists, and <em>Kesavananda</em> basic structure impose <em>legal</em> limits on the highest law-making body. Austin must demote those limits to positive morality or deny they are law. That is the critique paragraph, not “Austin is useless.” Residual use: the sanction picture still maps BNS punishments better than it maps Article 21. Hart’s gunman: being obliged is not having an obligation; power-conferring rules (a will, a contract, a statute that binds its maker) are not commands. Kelsen replaces the person-sovereign with an impersonal ought-pyramid.",
        "Close: the quotation is true as a programme for a command-shaped criminal OS and false as a map of a limited constitutional republic. Write the kernel, four critiques, the Indian limit, and one residual use. The command unpack (general versus particular, tacit custom, laws improperly so called) lives on the Austin drill if this 20-marker wants more machinery; do not also write Savigny."
      ])
    ],

    "j-historical": [
      A("theme", "C", "20", "Historical School — Savigny and Maine. Distinguish Historical and Analytical schools", [
        "Historical jurisprudence protests both natural-law eternal codes and analytical legislation-worship. Law is an organic growth, like language. Friedrich Karl von Savigny (1814, the anti-codification pamphlet against Thibaut) gives <em>Volksgeist</em>: the common consciousness of a people, expressed first in custom, then in juristic working-out. Legislation is late and dangerous if it cuts against that spirit. Lawyers are specialised organs of the Volksgeist, not village poets. Stages often taught: political (custom), technical/juristic, legislation. Critiques: whose Volk? Romantic nationalism; waiting for spirit can be an alibi against abolishing sati, slavery, or untouchability; the Indian Constitution is a deliberate transplant against parts of “people’s custom.”",
        "Sir Henry Sumner Maine (<em>Ancient Law</em>, 1861): progressive societies move from status to contract — rights once fixed by birth, family, and caste become arrangements of individual agreement. Agencies of change: legal fictions, equity, legislation. Indian use: Maine wrote on village communities as a colonial administrator-scholar. Critique: linear Victorian progress; modern labour, consumer, and reservation law re-create status as protective classification. The Contract Act 1872 is Maine’s direction; the Industrial Disputes Act is the counter-movement.",
        "Worked Indian illustration: Hindu Code Bills and the 1872 Contract Act are anti-Savigny documents — midnight-ish codes. Personal law that still keys rights to birth-status is a Maine leftover. A 20-marker that narrates Magna Carta has written legal history, not historical jurisprudence.",
        "Analytical versus Historical: present logical structure versus past organic growth; sovereign versus people; legislation versus custom; universal concepts versus national peculiarity. Best close: modern legal science needs both — Hart’s secondary rules <em>and</em> a story of how the rule of recognition got there. Do not confuse this distinguish with the logbook-versus-hypothesis card (historical jurisprudence versus legal history)."
      ]),
      A("stock CCS", "B", "10", "Savigny’s Volksgeist", [
        "Volksgeist is not a mystical slogan. It is Savigny’s hypothesis that law is the organic product of a people’s common consciousness, expressed first in custom and then in the juristic work of lawyers, and that a committee cannot manufacture that spirit on a timetable. The 1814 target was a hasty German civil code. Legislation is late; a premature code cuts living tissue. Indian critique, written in full: the Constitution, the IPC/BNS, and the Contract Act did not wait for a single Hindu or Indian Volksgeist. They are conscious transplants. Whose Volk, in a caste-plural society, is the second critique. Residual use: Savigny still explains why rules that ignore how a people actually marry, farm, or worship become paper law — Ehrlich’s living law is the sociological cousin of that warning."
      ])
    ],

    "j-socio": [
      A("Dec 2024 & 2023", "C", "20", "Dean Roscoe Pound’s theory of Social Engineering", [
        "Sociological jurisprudence studies law in action: effects, institutions, pressure groups. It is a protest against Austin’s will of a legally unlimited sovereign and against Savigny’s romance of the past as the only teacher. Features: functional approach; law as balancer of interests; interdisciplinary method; social justice. Ancestors: Ihering (purpose; struggle for rights); Ehrlich (living law versus paper law). Pound’s kernel: law is social engineering — satisfying the maximum of wants with the minimum of friction and waste.",
        "Inventory, then send the examiner to the interests card if they want the full list: Individual (personality, domestic, substance), Public (State as juristic person), Social (security, institutions, morals, resources, progress, individual life). Jural postulates are the civilisation’s default assumptions; they change. The fully written Indian collisions — Oleum gas / Vellore as environment versus industry, and Indra Sawhney as reservation versus open competition — are on the Pound-interests card. In this essay, write one of them in four to six sentences so the 20-marker has an engineering act, not only a taxonomy.",
        "Léon Duguit, if time: social solidarity — interdependence of division of labour — binds even the State; rights and property are social functions (Article 39(b)/(c) is the Indian echo). Duguit kills Austin’s illimitable sovereign from the French public-law side. Marxist contrast: Pound patches the machine; Marx asks who owns it.",
        "Critiques: who weighs?; friction is political; American progressive bias; measuring waste is hand-waving. Close: for CCS, Pound is the highest-yield sociological name because Indian public law actually schedules overlapping claims. Recite IPS, land Mehta or Indra Sawhney, then one limit on the metaphor."
      ]),
      A("Dec 2024", "A", "4", "Social Solidarity (Duguit)", [
        "Léon Duguit: there is no metaphysical sovereign and no subjective right as a mysterious will-power. There is social solidarity — the interdependence created by division of labour. Law is the body of rules that must exist because society exists; even the State is under those rules. Rights are social functions; property is a social function. Indian landing: Directive Principles, especially Article 39(b) and (c), and the idea that ownership is not Austin’s gift. Critique in one line: solidarity can be conservative (“stay in your function”), and “must” slides from is to ought. Do not restart Pound’s IPS inventory on a 4-marker."
      ])
    ],

    "j-realism": [
      A("Dec 2024", "C", "20", "American modern realism is a combination of analytical positivists and sociological approaches. Comment.", [
        "Agree, with a spine. American Legal Realism (1920s–40s) asks what courts and officials actually do. Holmes (1897): the prophecies of what the courts will do in fact, and nothing more pretentious, are what I mean by the law. Wash law with cynical acid; the bad man cares about courts, not sermons. Llewellyn’s rule-scepticism: paper rules under-determine outcomes; the paper rule is the digest, the real rule is official practice. Frank’s fact-scepticism (<em>Law and the Modern Mind</em>, 1930): the wild card is fact-finding — witnesses, prejudice, the trial judge’s hunch; appellate doctrine is an upper-court myth.",
        "Why analytical: Realists keep a positivist spine. Law is official behaviour, not natural law, not a moral checksum on validity. They are allies of Austin and Hart against Aquinas on the existence question, even while they smash Austin’s command picture and Hart’s tidy core of settled meaning. Why sociological: they explode the idea that the logic of rules explains decisions; they demand study of behaviour, economics, psychology, docket reality — law in action, Pound’s neighbourhood, without Pound’s tidy interest-balancing, which they distrust as too pretty.",
        "Worked Indian illustration: two identically charged theft trials, same BNS section, different convictions because of how the trial judge heard the witnesses. Frank says the law that mattered was fact-finding, not section 303. Hart replies that the core of “movable property taken dishonestly” still decided the charge; the penumbra is the evidence. PIL creativity and sentencing disparity are realist observations, not a holding that “rules do not exist.”",
        "Critiques: cynicism that dissolves obligation; underplays that rules constrain easy cases (Hart); American appellate culture is not an Indian district court; “might makes law.” Scandinavian contrast, one paragraph if the 2023 “Realist Movement” paper: Hägerström, Olivecrona, Ross — rights as mystical psychological facts. Close: yes, a combination — analytical in refusing natural law, sociological in studying action — minus Austin’s bark and minus Pound’s engineering confidence."
      ])
    ],

    "j-marx": [
      A("theme", "C", "20", "Discuss the Marxist / economic approach to law", [
        "Marx and Engels: the economic base — forces and relations of production — conditions the superstructure of State, law, and ideology. Law presents class interest as universal right. “Freedom of contract” in a factory society is not a natural liberty; it is the legal form of a wage relation. The State is not Austin’s neutral sovereign; it is organised class power with a legal face. Property rights are historically specific, not Lockean nature. Features to list: historical materialism; law as class instrument; the contested “withering” of law in a classless society; critique of formal equality; ideology — legal consciousness hides exploitation.",
        "Worked Indian illustration: section 10 of the Contract Act looks like Maine’s high-water free agreement. A mill-owner and a factory worker are not equal contracting atoms; consideration is the legal form of a class relation. Labour statutes and <em>Bandhua Mukti Morcha</em> are counter-movements. Colonial codes protecting trade and land revenue; the long property fight (repealed Article 31, Article 300A); the Preamble’s socialist word (42nd Amendment) — write these as production relations, not as a party pamphlet. Pashukanis (optional depth): the legal subject and the contract mirror commodity exchange; Pound reforms capitalism, Pashukanis thinks the legal form itself is capitalist.",
        "Critiques: reductionism (family law, religious personal law, and harsh penal codes in socialist States are not a simple base-superstructure cartoon); judicial agency; human-rights vocabulary after 1945; India’s mixed economy and constitutional liberalism. Pair with Sociological: both attack Austin. Pound wants better engineering inside the market-State. Marx wants a different machine. Close: the approach is residual high-value for labour, property, and “equal bargaining” essays; it is not a key that opens every Part III lock."
      ])
    ],

    "j-hist-vs-legalhist": [
      A("stock CCS", "B", "10", "Distinction between historical jurisprudence and legal history", [
        "Legal history is the descriptive chronology of a particular legal system — a logbook of statutes, courts, conquests, receptions, and repeals. It answers: what happened here, and in what order? Example: the East India Company courts; the Contract Act 1872; how IPC 299/300 became BNS 100/101. Method: archive, gazette, case-report chronology. Output: a timeline of one repository. It does not, by itself, tell you whether law is command, spirit, or solidarity.",
        "Historical jurisprudence is a theory of law that uses history to explain what law is and how it grows. Savigny’s Volksgeist is not a date; it is a hypothesis that law is the organic product of a people’s consciousness and that hasty codes fail. Maine’s status-to-contract is not a king-list; it is a developmental law of progressive societies. Method: comparative history in the service of theory. Output: a claim you can contrast with Austin and Pound.",
        "Engineer analogy: legal history is git log of one repo; historical jurisprudence is a theory of how ecosystems of repos evolve. Exam trap: “Discuss the Historical School” is not an invitation to narrate Magna Carta. Two Savigny paragraphs, Maine’s formula, and this distinction beat five pages of dates. Indian pair: 1860 IPC enactment is legal history; Maine on village communities as a theory of status is historical jurisprudence. Close: a good lawyer needs the logbook and the hypothesis. They are not the same subject."
      ])
    ],

    "j-austin-cmd": [
      A("Dec 2023", "C", "20", "Austin’s command theory — sovereign, sanction, habit of obedience", [
        "For Austin, a law properly so called is a general command of a sovereign, backed by a sanction, in an independent political society marked by habitual obedience of the bulk. A command is a wish of a rational being, signified to another, with an evil to be incurred if it is not complied with. That evil is the sanction. A friend’s advice is not law (no sovereign evil). Social boycott is not Austin’s legal sanction. General commands (to a class, standing) are laws; particular commands (hang this person) are occasional — executive or judicial, not “laws.”",
        "Sovereign: a person or determinate body, not in habit of obedience to a like superior, who receives habitual obedience from the bulk. Marks: determinate; legally illimitable (political and moral limits do not count as legal limits); bulk obedience (rebels and infants can be ignored). Continuity problem: when Rex I dies, habit has not yet formed around Rex II — Hart will call this a defect of the habit picture. Province: positive law versus positive morality (international law, fashion, club rules) versus divine law. Laws improperly so called include declaratory, repealing, and imperfect (no sanction) laws. Custom and judges are saved, awkwardly, as tacit commands — the sovereign permits by not intervening.",
        "Worked Indian illustration: Parliament looks Austinian until Article 13, judicial review, federal lists, and basic structure impose legal limits on the highest law-making body. Austin must demote those limits to positive morality. Residual use: BNS punishments still look like sanctioned commands; Article 21 does not. Four critiques: custom and precedent are not easy commands; international law exists without a global sovereign; constitutions bind sovereigns; habit is sociological smuggling; private law (a will) looks odd as a threat.",
        "Close: Austin is a powerful model of a criminal command operating system, not a map of a limited constitutional republic. Quote command, sovereign, sanction, habit; land Kesavananda as critique; keep Bentham as the reform cousin, not a second sovereign."
      ]),
      A("theme", "B", "10", "Why Austin demotes international law — and why that matters in India", [
        "International law has no determinate global sovereign habitually obeyed by the bulk of a world society, and no regular sanctioned evil of Austin’s type. Therefore, for Austin, it is positive morality — analogue, not law properly so called. Club rules and (on his terms) much of constitutional convention travel the same road. The Indian sting: a Constitution that legally limits Parliament looks, to Austin, like positive morality too. That is why the 10-marker is not a trivia question about treaties. It is the same structural failure that Article 13 and basic structure expose. Hart and Kelsen both try to save international law as a system (borderline for Hart; a possible separate Grundnorm for Kelsen). Close: demotion of IL is the symptom; legally unlimited sovereignty is the disease."
      ])
    ],

    "j-hart-rules": [
      A("theme", "B", "10", "Hart’s primary and secondary rules. What is the rule of recognition?", [
        "A society with only primary duty-rules (do not kill; pay tax) suffers uncertainty (what is the rule?), staticity (how do we change it except by slow custom?), and inefficiency (who decides disputes?). Secondary rules are rules about rules: recognition (the master test of validity), change (power to legislate, repeal, amend, including limits), and adjudication (power to decide and to make the decision authoritative). A legal system exists when primary rules are joined to secondary rules and officials actually practise a rule of recognition.",
        "The rule of recognition is a social rule practised by officials, not a command and not a Kelsenian presupposed ought. External point of view: the sociologist predicts. Internal point of view: officials use the rule as a standard of criticism — “that is not law.” Being obliged (gunman) is not having an obligation (rule). Power-conferring rules — make a will, form a company — have no bark.",
        "Worked Indian illustration: do not write “the Constitution is the rule of recognition” as if that ended the debate. Officials, including the Court, also practise amendment limits after <em>Kesavananda</em>: some Article 368 outputs are treated as invalid even though the text of 368 was followed. That practised overlay is the Hartian sentence. Open texture: “no vehicles in the park” clearly catches a bus; a toy car is penumbra. Close versus Austin: habit is not a rule; the sovereign can be legally limited. Versus Kelsen: the top is practised, not presupposed."
      ]),
      A("theme", "C", "20", "Hart’s Concept of Law as an upgrade of Austin (and a reply to Realists)", [
        "Hart upgrades Austin rather than decorating him. Obligation is not a gunman situation scaled up. Habits do not explain why Rex II is already sovereign, why the sovereign can be bound, or why a contract is law. The union of primary and secondary rules is the new picture. Recognition, change, and adjudication are the patch set for a pre-legal world’s three defects. The rule of recognition is officials’ practice, internal point of view included.",
        "Reply to Realists: rules have a core of settled meaning; scepticism is for the penumbra. Easy cases are rule-governed; hard cases involve discretion. Reply to Kelsen: validity still chains, but the base is a social rule, not a transcendental ought. Indian landing written in full: Constitution plus legislation plus precedent is the pedigree; basic structure is a practised overlay; a registered will is law because secondary rules of change and recognition say so — nobody was commanded at the signing.",
        "Critiques: official practice can look circular; open texture dumps hard cases into discretion; later “soft positivism” (moral tests if the recognition rule includes them) is extra credit, still a pedigree story, not Natural Law. Close: Hart is the analytical name to write when the question is “what is a legal system?” Austin remains the name when the question is command and sanction. Do not mash them."
      ])
    ],

    "j-analytical-vs-natural": [
      A("theme", "B", "10", "Distinguish the Analytical and Natural Law schools", [
        "Analytical positivism asks what is valid law in this system. Validity is pedigree — command, norm, or rule of recognition — not goodness. Austin, Kelsen, Hart. You can say “this is law but it is wicked.” Natural law asks what is law worthy of the name. Law participates in reason or justice. Aquinas, Locke, Stammler, Fuller; Radbruch at the extreme. Validity and merit leak into each other.",
        "Nazi-law problem, written in full: a statute impeccably passed and enforced that strips a class of legal personality is still “law” for Austin/Kelsen/Hart, then condemned politically (Hart 1958: keep the existence question clean so criticism stays possible). For Aquinas, Radbruch, and Fuller (if the inner morality fails — generality, publicity, prospectivity, clarity, non-contradiction, possibility of compliance, constancy, congruence of official action) it may fail as law. Do not write that positivists love injustice. They refuse to let disagreement about justice decide existence.",
        "Indian echo: Article 13 pedigree is the analytical spine; Preamble justice, <em>Maneka</em>’s just-fair-reasonable reading of “procedure established by law,” and basic-structure morality are natural-law pressure on a positivist text. Stammler’s variable content is the revival name CCS wants if the 10-marker stretches. Close: is versus ought; names; one wicked-statute paragraph; one Indian pair."
      ])
    ],

    "j-socio-vs-hist": [
      A("theme", "B", "10", "Distinguish the Historical and Sociological schools", [
        "Shared enemy: law as the whim of a legally unlimited sovereign. Fork: Savigny looks backward — custom, Volksgeist, organic growth; legislation is late and dangerous. Pound looks sideways and forward — interests now, jural postulates of this civilisation, legislation and judging as engineering tools. Maine’s status-to-contract is a historical law of motion. Pound’s social interests can justify labour codes Maine would have called a return to status. Duguit’s solidarity is interdependence now, not folk-spirit then.",
        "Method: Historical uses comparative legal history in aid of theory. Sociological is empirical and functional — effects, institutions, pressure groups. Attitude to reform: Historical is conservative-leaning (do not cut organic tissue). Sociological is reformist-leaning (re-balance the scheduler).",
        "Worked Indian illustration: personal-law persistence is a Historical leftover (status still organises the family). Hindu Code Bills and later gender-equality statutes are Pound-engineering against that leftover. The Constitution did not wait for a single Volksgeist; it is a sociological document with historical materials. A 10-marker that only narrates Savigny’s 1814 pamphlet, or only lists Pound’s IPS, has missed the fork. Close: grow versus schedule; Savigny/Maine versus Pound/Duguit; one Indian pair."
      ])
    ],

    "j-law-morals": [
      A("Dec 2023", "B", "10", "Law and Morals", [
        "Law and morals intersect; they are not identical. Three maps. Overlap: homicide, theft, fraud — illegal and immoral. Law without moral heat: tax rates, limitation periods, company filing fees. Morals without legal enforcement: many private lies; some religious duties the State will not police. The 10-marker dies if it says “law equals morals.”",
        "Positivist separation (Austin, Kelsen, Hart): a norm can be valid and iniquitous. Hart’s 1958 essay keeps the existence question clean so criticism stays possible. Nazi “laws” can be called law, then condemned — or, if you prefer Radbruch, extreme injustice drops out of law. CCS usually wants the separation plus a sociological critique, not a Radbruch seminar.",
        "Hart versus Fuller: Fuller loads procedure with an inner morality of law — eight ways a system fails to be law (generality, publicity, prospectivity, clarity, non-contradiction, possibility of compliance, constancy, congruence of official action). Hart: those are principles of efficacy, not a moral test of validity; a wicked but formally complete code is still law. Hart versus Devlin (Wolfenden Report, 1957): Devlin’s disintegration thesis — shared morals bind society, so the criminal law may enforce the moral majority. Hart, Mill-flavoured: harm principle; private immorality is not the law’s business.",
        "Indian illustration, written in full: sati was a customary “moral” practice in some communities; the statute book banned it. That is law against popular morals, not law copying them. Constitutional morality versus popular morality is the modern cousin (<em>Navtej Johar</em> is extra credit, not Sem-1 core). Close: overlap, separation, Fuller, Devlin, sati. Do not restart the Analytical 20-marker."
      ])
    ],

    "j-akh": [
      A("Dec 2023", "B", "10", "Difference between Austin and Kelsen", [
        "Austin explains law as the general command of a determinate sovereign, habitually obeyed, backed by a sanction — an evil visited on disobedience. Kelsen explains law as a pure hierarchy of norms, each authorised by a higher norm, ending in a presupposed Grundnorm. Both separate validity from moral merit. That is the only safe generalisation; the rest is contrast.",
        "What law is: command of a person versus impersonal ought. Who sits at the top: a legally illimitable political superior versus a presupposed base (“the historically first constitution ought to be obeyed”). Sanction: threatened evil versus a directed coercive act stipulated by a norm. Morals: both outside jurisprudence; Kelsen more radically (even the science must be pure of sociology). Custom and international law: awkward tacit commands and “positive morality” for Austin; custom is law if a higher norm so provides, and international law can be a system with its own Grundnorm, for Kelsen.",
        "Indian landing, written in full: Article 13 and <em>Kesavananda</em> kill the illimitable sovereign — the Constitution legally limits the highest law-making body, which Austin must demote to positive morality. 26 January 1950 is a Grundnorm shift from colonial legality; basic structure is then a fight over whether even the highest amending norm is unconditioned, a fight that would make Kelsen uneasy. Close: allies against natural law, enemies on the picture of a legal system. Hart is a third column if time — practised recognition versus both the gunman and the fiction — but this 10-marker is the pair."
      ]),
      A("theme", "C", "20", "Salient features of the analytical school. Distinguish Austin, Kelsen and Hart", [
        "Analytical jurisprudence asks what law is as a social fact and a logical system, not what it ought to be. Features: positivism (validity is pedigree, not justice); present law rather than origin-myth; logic and definitions; the State or official practice as the centre; morals parked as positive morality, purity, or a separate existence question. The school is not “all Englishmen who hate natural law.” It is three kernels: command, pyramid, ruleset.",
        "Austin: sovereign, command, sanction, habit. Kelsen: norm, validity chain, Grundnorm, State as order personified. Hart: union of primary duties and secondary power-rules — recognition, change, adjudication — and a rule of recognition officials actually use. Hart versus Austin: gunman is not obligation; power-conferring rules are not commands; the centre can be legally limited. Hart versus Kelsen: social practice versus transcendental ought; English ordinary language versus continental norm-logic.",
        "Indian landings: Kesavananda wounds Austin; 26 January 1950 is a Kelsen sentence; the Court’s practised basic-structure overlay is a Hart sentence. Weak spots: Austin at limited constitutions and custom; Kelsen at a fictional base and empty justice; Hart at circular official practice and open texture. Close: dump a six-row table from memory, then three Indian sentences. Do not write Pound, Savigny, or a definition parade on this distinguish."
      ])
    ],

    "c-nature": [
      A("Dec 2024", "B", "10", "Indian Constitution neither federal nor unitary but quasi-federal — Discuss", [
        "Article 1 says India is a Union of States, not a federation of contracting members who may secede. The drafting choice of “Union” is itself the exam sentence: the Union is indestructible. K.C. Wheare’s label “quasi-federal” is the classroom landing — federal hardware with a unitary turbo — not a team to join.",
        "Federal hardware, written as a list the examiner can tick: dual polity (Union and States); a written Constitution; supremacy of the Constitution; a rigid amendment process (Article 368, now with a basic-structure overlay); division of powers in the Seventh Schedule; an independent judiciary with judicial review; imperfect bicameralism (Rajya Sabha as a House of States, weaker than a US Senate). Unitary turbo: a strong Centre; single Constitution; single citizenship; unified judiciary; All-India Services; residuary with the Union (Article 248 / List I-97); emergency provisions (Articles 352, 356, 360) that can clock the Centre to one hundred per cent; Parliament’s power to legislate on the State list in listed situations (249, 250, 252, 253); Article 3 — States can be reorganised without their consent as a veto; nominated Governors.",
        "Doctrine moved. <em>State of West Bengal v Union of India</em> (1963) emphasised Centre’s strength: this Union is not a league of States. <em>S.R. Bommai</em> (1994) treats federalism (and secularism) as a basic feature and makes Article 356 justiciable in principle. The honest close is Wheare plus Bommai: federal with a strong Centre, not “neither” as a shrug, and not “unitary” as a rant. Parliamentary form is a neighbouring question (Articles 74–75, collective responsibility to the Lok Sabha); dump it only if the paper also asks form of government."
      ]),
      A("2022", "A", "4", "Parliamentary form of government", [
        "India’s executive is parliamentary, Westminster-derived. The President is the nominal head (Article 53 read with 74); the real executive is the Council of Ministers, headed by the Prime Minister, collectively responsible to the Lok Sabha (Article 75(3)). Features: majority rule; political homogeneity of the cabinet; individual as well as collective responsibility; the possibility of dissolution of the lower house. Contrast presidential (US): fixed tenure, a separately elected real executive, sharper separation of powers. One-line close: the Prime Minister lives only while the lower house keeps the process manager running."
      ])
    ],

    "t-intro": [
      A("Dec 2024", "C", "20", "Mere causing of actual loss is not necessarily a tort but mere wrong without actual loss is a tort — Explain with cases", [
        "A tort is a civil wrong, other than a breach of contract or trust, for which the ordinary remedy is unliquidated damages. Winfield: liability from breach of a duty primarily fixed by law, toward persons generally. Salmond: a civil wrong redressable by a common-law action for unliquidated damages. The maxim pair in the question is the spine, not a decoration.",
        "<strong>Damnum sine injuria</strong> — damage without violation of a legal right — is not a tort. Actual loss, even painful loss, is not enough if no right was breached. <em>Gloucester Grammar School</em> (1410): a rival school took pupils; the old master had no action for competition. <em>Mayor of Bradford v Pickles</em> (1895): extracting water on one’s own land, even maliciously, was not a tort where no right of the neighbour was violated; motive generally does not convert a lawful act into a tort (<em>Allen v Flood</em> is the cousin). <em>Mogul Steamship</em>: competition by lawful means. Indian flavour: loss from a competitor’s lawful trade, or from a cinema showing a film that hurts religious sentiment without violating a legal right, is damnum without injuria.",
        "<strong>Injuria sine damno</strong> — violation of a legal right without proved actual loss — is a tort. The law protects the right, not the rupee. <em>Ashby v White</em> (1703): a returning officer wrongfully refused a vote; the plaintiff recovered though the preferred candidate won. <em>Marzetti v Williams</em>: a banker’s refusal to honour a customer’s cheque when funds existed. Trespass to land is the everyday illustration: stepping on land without permission is actionable per se even if the grass is unharmed.",
        "Constituents, to close the 20-marker: a wrongful act or omission; legal damage (injuria); a legal remedy (usually damages). Mental element varies by tort and is not the question’s centre. Pigeon-hole versus Winfield is a Section A cousin, not this essay’s body. Close by answering the verb: mere loss is not a tort; mere legal wrong, even without loss, is. Injuria is the legal hit."
      ]),
      A("Dec 2024", "A", "4", "Pigeon-hole theory (short — home is the dedicated card)", [
        "Salmond: liability in tort exists only if the facts fit a named tort — negligence, defamation, trespass — a closed set of pigeon-holes. Winfield: there is a general principle of liability for unjust harm, with defences, so new holes can be cut. Indian courts are pragmatic: they still speak in nominate torts but stretch negligence and constitutional torts. One-line close: CCS loves the label; do not write Rylands here unless the short note is strict liability."
      ])
    ],

    "cr-homicide": [
      A("Dec 2024 BNS / Dec 2023 IPC", "C", "20", "Culpable homicide versus murder under BNS, with case law", [
        "All murder is culpable homicide; not all culpable homicide is murder. Culpable homicide is the genus; murder is the species — the bullseye. Write BNS numbers first, IPC in brackets for older PYQs.",
        "Culpable homicide, BNS 100 (IPC 299): causing death by an act with (a) intention of causing death, or (b) intention of causing such bodily injury as is likely to cause death, or (c) knowledge that the act is likely to cause death. Murder, BNS 101 (IPC 300), is culpable homicide plus one of four special mental states: (1) intention to cause death; (2) intention to cause bodily injury that the offender knows is likely to cause death of that person; (3) intention to cause bodily injury sufficient in the ordinary course of nature to cause death; (4) knowledge that the act is so imminently dangerous that it must in all probability cause death, committed without excuse. Punishment for murder is BNS 103 (IPC 302). If an exception applies, the case drops to culpable homicide not amounting to murder, BNS 105 (IPC 304).",
        "The five exceptions, listed: grave and sudden provocation; private defence exceeded in good faith; public servant exceeded; sudden fight without premeditation; consent of a deceased above eighteen in limited settings. Teaching distinction: “likely” (culpable homicide) versus “sufficient in the ordinary course of nature” (murder clause 3). <em>Reg v Govinda</em> (1876 Bom) is the classroom case. <em>Virsa Singh v State of Punjab</em> (1958): for clause 3, the injury intended must be the injury inflicted, and that injury must be objectively sufficient to cause death — no need to intend death. <em>State of A.P. v Rayavarapu Punnayya</em> restates the genus/species map.",
        "BNS 106 (IPC 304A) is a different product: rash or negligent death, not culpable homicide at all. <em>Jacob Mathew</em> (2005) for criminal medical negligence — gross, not mere error. Section 103(2) (group murder on specified identity grounds) is a BNS-era hook; verify the text. Close: definitions, four clauses, five exceptions, Virsa Singh, 105 demotion, 106 leftover. Do not write a private-defence essay unless the facts need an exception."
      ]),
      A("theme", "B", "10", "Virsa Singh and clause 3 — intended injury, objectively sufficient", [
        "Clause 3 of murder (BNS 101 / IPC 300) is the examiner’s favourite because students confuse it with intention to cause death. <em>Virsa Singh v State of Punjab</em> (AIR 1958 SC 465): it is enough that the accused intended the injury that was inflicted, and that that injury was sufficient in the ordinary course of nature to cause death. There is no third requirement that the accused intended death, or knew the injury was likely to cause death. A spear thrust into the abdomen, intended as that thrust, objectively sufficient, is murder even if the accused “only meant to injure.” Contrast BNS 100’s “likely”: probability, not sufficiency. Close: intended injury plus objective sufficiency; do not smuggle intention to kill into clause 3."
      ])
    ],

    "k-eng-vs-indian": [
      A("Dec 2024", "C", "20", "Consideration — kinds; English versus Indian law", [
        "Consideration is the price for a promise — the act, abstinence, or promise that moves at the promisor’s desire. English spine, recited first. Consideration must move from the promisee; a stranger who paid cannot sue (<em>Tweddle v Atkinson</em>, 1861). Past consideration is generally not good (<em>Eastwood v Kenyon</em>; <em>Roscorla v Thomas</em>), unless the act was done at the promisor’s request with an understood later promise. Consideration need not be adequate but must be sufficient in law — a peppercorn will do; natural love and affection will not. Privity: only parties can sue (<em>Dunlop v Selfridge</em>).",
        "Indian section 2(d) widens two pipes. When, at the desire of the promisor, the promisee <em>or any other person</em> has done or abstained, or does or abstains, or promises to do or abstain, that is consideration. First widening: consideration need not move from the promisee. <em>Chinnaya v Ramayya</em> (1882): a sister could sue as promisee though consideration moved from her mother. Second widening: the three tenses — has done, does, promises — so past consideration is good if it was at the promisor’s desire.",
        "What India did not abolish: privity of parties. <em>M.C. Chacko v State Bank of Travancore</em> (1969); <em>Jamna Das</em>: a beneficiary who is not a party still cannot sue unless a trust, family, acknowledgement, or similar exception applies. Students mash “any other person” into “strangers can always sue.” That is the 20-marker trap. Section 25 then cuts three no-consideration doors English law would usually refuse: love and affection (written, registered, near relation); compensation for a past voluntary act; a written promise to pay a time-barred debt.",
        "Kinds, if the question asks: executory (promise for promise), executed (act for promise), past (act already done at desire). Close: India widened the consideration pipe and kept the parties pipe narrow, then cut three statutory windows in section 25. Dump the table: who may furnish; past; love and affection; time-barred debt; privity. Chinnaya plus Tweddle plus Chacko."
      ]),
      A("theme", "B", "10", "“Any other person” is not a licence for strangers to sue", [
        "Section 2(d) lets consideration move from the promisee or any other person at the promisor’s desire. That is a rule about who may furnish the price, not about who is a party. <em>Chinnaya v Ramayya</em> is a promisee suing, with consideration from a third person. <em>Tweddle v Atkinson</em> is the English opposite: the son could not sue because consideration had not moved from him and he was not a party in the English sense. Indian privity still follows the English parties pipe: <em>M.C. Chacko</em> — a stranger to the contract cannot sue merely because he is a beneficiary, unless an exception (trust, family settlement, acknowledgement, statutory right) adds him to the ACL. Close: 2(d) wide, privity narrow. That sentence is the 10-marker."
      ])
    ]
  };
})(window);
